Update patch set 5
Patch Set 5:

Liam, per POLICY-1406 (moving to JDK 11), using jaxb won't work since I see imports of javax.xml.bind .. package.   Probably should give it some thought for a contingency plan.

I found this thread that gives you potential solutions, the maven dependency one would be worth to explore (if you don't do that already).   I didn't run a dependency tree.

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

Patch-set: 5